# [[Root]]
cmake_minimum_required(VERSION 3.5)

project(ModernC)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)


# [[Options]]
option(MODERNC_BUILD_SHARED_LIBS "Build shared libraies by Default" ON)


# [[Binaries]]
if(MODERNC_BUILD_SHARED_LIBS)
    set(PROJECT_LIBS_TYPE SHARED)
else()
    set(PROJECT_LIBS_TYPE STATIC)
endif()


file(GLOB_RECURSE PROJECT_SOURCES_FILES "${CMAKE_CURRENT_LIST_DIR}/src/*.c" "${CMAKE_CURRENT_LIST_DIR}/include/*.h")
add_library("${PROJECT_NAME}" ${PROJECT_LIBS_TYPE} ${PROJECT_SOURCES_FILES})
target_include_directories("${PROJECT_NAME}" PUBLIC "${CMAKE_CURRENT_LIST_DIR}/include")

if(MODERNC_BUILD_SHARED_LIBS)
    set_target_properties("${PROJECT_NAME}" PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
endif()


# [[Tests]]
if(PROJECT_IS_TOP_LEVEL)
    add_subdirectory("test")
endif()
